[build]
dockerfilePath = "services/knowledgebase_ingestion/Dockerfile"
rootDirectory = "."

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/ready"
healthcheckTimeout = 100

